### PR TITLE
wname: Support utf8.

### PR DESCRIPTION
**Pull request by onodera-punpun**

### CODE REVIEW

**Comment by dcat** [comment]
Please return a string, and remember to `free() `

**Comment by nounoursheureux** [comment]
I thought that we did not want to support EWMH, but _NET_WM_NAME is an EWMH property

**Comment by dcat** [comment]
`wname` is moved to opt

**Comment by nounoursheureux** [comment]
Oops I didn't notice this, it makes sense then :+1:

**Pull request closed without merging**
