### PR TITLE
new tool: chwn

### PR DESCRIPTION
**Pull request by pranomostro**
Sorry again for the contrib mess.
chwn changes the name of the given window.
I tried to comply with the coding style of
wmutils.

### CODE REVIEW

**Comment by pranomostro** [comment]
Small additional fix: remove last mention of wname in wmutils.1

**Comment by pranomostro** [comment]
> IF YOUR PULL REQUEST DOESN'T REFER TO A VALID ISSUE, IT WILL BE DISCARDED.

Is it okay if I don't open an issue on this one, since it's not technically an issue?
Or should I put chwn into opt instead?

**Comment by wildefyr** [comment]
I think this is something much more suited towards opt. After all, `wname` is in opt and also refers to retrieving window names.

**Comment by pranomostro** [comment]
Okay. I'll create a pull request at opt.

**Pull request closed without merging**
