### PR TITLE
Fix wrs absolute mode

### LINKED ISSUE #33: wrs absolute mode broken
When using ```wrs``` in absolute mode sometimes (a lot of the time) the size of the window changes to a size completely different from the desired size (usually a lot smaller, most of the time not even the correct aspect ratio).

I can reproduce this most of the time with ```wrs -a 500 500 $some_window_id```. Notice how the resulting window is not square.

Tested with urxvt on a 1080p screen without a WM running.

Context of finding this bug:

I am currently writing wrappers for ```wmv``` and ```wrs``` that move the mouse pointer with them to fix some of the inconveniences of the detail fix. The ```wrs``` wrapper also introduces arguments that make it possible to keep the center of the window in the same place after a resize or resizing to the left. The ```wmv``` wrapper is mostly finished, while the ```wrs``` wrapper still needs work. In particular that is some fixes for center-keeping resizes on the right edge of the screen and absolute resizing (should work in theory, but discovered this ```wrs``` bug)

### PR DESCRIPTION
**Pull request by Ferdi265**
Fixes #33 

The problem is that absolute mode in `wrs` did this: (Variable names are pseudo code)

```
x = param_new_width; // parameter, not actually in code
y = param_new_height; // parameter, not actually in code

x -= r->x + r->width;
y -= r->y + r->height;

new_width = r->width  + x;
new_width = r->height + y;
```

which can be simplified to this:

```
new_width = r->width - r->width - r->x + param_new_width;
new_height = r->height - r->height - r->y + param_new_height;
```

In relative mode this is like this (which makes sense):

```
new_width = r->width + resize_by_x;
new_height = r->height + resize_by_y;
```

The correct absolute mode would look like this:

```
new_width = r->width - r->width + param_new_width;
new_height = r->height - r->height + param_new_height;
```

As you can see, the old width/height cancels out.

This makes `wrs` behave properly when used in absolute mode.

### CODE REVIEW

**Comment by Ferdi265** [comment]
Removed the code that changes window stack order in `wrs` (brings changed window to top). That's the job of `chwso`.

Compared this to `wmv`, which also doesn't change the stack order, so I thought I'd fix that difference. IMO either both should do it or none of them.

Actually... It REALLY should be done by `chwso`, UNIX philosophy and all, `wrs` and `wmv` shouldn't mess with stack ordering

**Comment by z3bratabs** [comment]
I think you misunderstand how absolute mode works in `wrs`. The coordinates it expects are the absolute coordinates to the size of the window, so for example, `wrs -a 500 500 $wid` will resize the window so that its bottom right hand-corner would be at coordinate 500x500.
It is not supposed to make the window 500x500 pixels. I can understand it might look odd, but when designing the tools in core, we tried to make all the tools easier to integrate together. The reason behind this behavior, is to be able to do this:

    wrs -a $(wmp) $wid

This will expand/shrink the window to the mouse cursor, which is extremely handy to resize windows with the mouse.

For the stacking order, this is a valid point, `wmv` and `wrs` should have the same behavior. Now, we need to figure which one should be the default. I agree that the tools should follow the "unix philosophy", but this catchphrase should not be an excuse for a stupid behavior. You should optimize for the 80%, not the 20%, and I truly can't think of a use case where you would not want to raise the window you're moving/resizing.

**Comment by Ferdi265** [comment]
This kind of makes sense. Though in that case it should be documented better. Also since X itself stores window width and height as the actual width and height and not as the coordinates of the lower right corner it makes it even less intuitive.

About the raising issue: I have a script that moves and resizes terminals to a standard size and location when they are spawned, but I don't want them to pop in front of my focused window (almost like stealing focus). With `wrs` current behaviour (and proposed `wmv`) behaviour, I'd have to explicity bring some windows back to the front or put others to the back after resizing. It messes with my workflow.

Though I agree that for interactive resizing anything different than bringing them to front doesn't make any sense.

So, case in point: For interactive usage: yes, bring to front; for automated scripts that execute on events not directly related to interactive use: bringing it to front might mess with some workflows.

What that means exactly is questionable. Maybe introduce another option on whether it should bring it to the front as well or add a `chwso -r` that use `wrs` and `wmv` in an interactive way (which might be tedious for things like `sxhkd` which normally expect just one command

**Comment by z3bratabs** [comment]
By having them raise the window, it makes it easier to use the tools alone, for example, with sxhkd. It also make makes resizing with the mouse easier (having to spawn 1 process instead of two, every 100ms or whatever the frequency is).
As I said, we should optimize the usage for the most obvious cases, and make it easier to deal with for the majority of users.
For your workflow, I don't understand why you would want to spawn a window without focusing it. Didn't you spawn it in order to use it after all?
Raising + focusing new windows is the behavior provided by 100% of the WMs I tried, and I understand why.
Nevertheless, if you ask for it, that's a valid use case, and it should have a solution.
On fact, it already have a solution: `wtp`. It lets you teleport windows at a special location, with a specific size, all that without raising the window. So if you run

    wtp 100 200 500 500 $wid

You'll end up with a square window, 500x500 pixel, at location 100,200. And it seems like that is what you want ;)

I'd rather have to use `chwso` in a script from time to time, when a really special case occur, rather than having to use it whenever I need to perform an operation on a window.

The goal is to make each tool good at what it tries to do. If you want to move a window, then all you need is `wmv`.

**Comment by z3bratabs** [comment]
After thinking about it, I think that the X server put new windows on top of the stack by default

**Comment by z3bratabs** [comment]
Closing this as not a bug

**Pull request closed without merging**
