### PR TITLE
killw: kill window instead of client

### PR DESCRIPTION
**Pull request by clehner**
Ref #15
To obtain old behavior of killing client, `xkill -id <xid>` can be used.
Or should this be another command / argument?

### CODE REVIEW

**Comment by z3bratabs** [comment]
This seems to work indeed. I wasn't aware of the `xcb_destroy_window()` function, good find, and thanks for the good find!

I don't know if we should completely give up the old behavior though. It has the advantage of killing frozen applications rather well. Perhaps add a `-k` switch to trigger it?

**Comment by Wildefyr** [comment]
That would work for me.

**Comment by clehner** [comment]
I'm finding now that some applications hang when the window is destroyed but the connection is kept open in this way (i.e. xev, tabbed). I also didn't realize there was `killwa` which does the WM_DELETE_WINDOW. I'm thinking now maybe killw should be left as it is, for killing clients, and killwa can be changed to use xcb_destroy_window as a fallback. Thoughts?

**Comment by z3bratabs** [comment]
The fact they hang like this might just be due to an incorrect handling of such an event in the said application. Just a supposition though... I won't be able to test anything by this week, but as far as I can tell, the patch you proposed worked rather well, and in case an application hangs, having tje ability to kill the client via a `-f` switch would be a plus.

The WM_DELETE_WINDOW method implies following a whole standard just for the ability to ask a window to close itself. If we start supporting this atom, then why wouldn't we support all the others? This is definitely not a route we want to take.
In case the client needs to close the window by itself, there is a way to do it within the client (pressing `q`, `^w`, `<esc>` or whatever).

I doubt anyone ever asked for a common binding to close all the ncurses applications, people just get used to the available ones, be it `q`, `^x` or `:q`, and don't complain about it.

This way, `killw` will only act as a "final solution" to close a misbehaving application, or a frozen one. Not as a generic solution.

**Comment by onodera-punpun** [comment]
I already created a tool that does exactly this using atoms, it's in contrib: https://github.com/wmutils/contrib/tree/master/killwa

**Comment by z3bratabs** [comment]
Due to a rollback of a bunch of commits, this PR can't be merged anymore and will thus be closed unmerged.

Could you please re-submit it with the actual HEAD? Otherwise, I can perform the change myself and give you credits for this commit. Whatever suits you best.

**Comment by clehner** [comment]
@z3bratabs I think the change here (xcb_kill_client -> xcb_destroy_window) would be better applied to `killwa`. However, I'm not using either command currently (went back to i3, for now) so I don't feel inclined to resubmit. You can incorporate it here if you think it makes sense.

**Pull request closed without merging**
